export const TeamJson = {
  teams: {
    teamId: "1",
    teamName: "Team-A",
    teamMembers: [
      {
        employeeId: "1",
        employeeName: "Akash Pradhan",
        loggedIn: "false",
        workStatus: "",
        seatNo: "1244",
      },
      {
        employeeId: "2",
        employeeName: "Gaurav Swain",
        loggedIn: "false",
        workStatus: "",
        seatNo: "713",
      },
      {
        employeeId: "3",
        employeeName: "Kumar Vivek",
        loggedIn: "false",
        workStatus: "",
        seatNo: "812",
      },
      {
        employeeId: "4",
        employeeName: "Swavi Kumar",
        loggedIn: "true",
        workStatus: "",
        seatNo: "765",
      },
      {
        employeeId: "5",
        employeeName: "Don",
        loggedIn: "true",
        workStatus: "",
        seatNo: "1234",
      },
      {
        employeeId: "6",
        employeeName: "Carleone",
        loggedIn: "true",
        workStatus: "",
        seatNo: "554",
      },
      {
        employeeId: "7",
        employeeName: "Helina",
        loggedIn: "true",
        workStatus: "",
        seatNo: "111",
      },
      {
        employeeId: "8",
        employeeName: "Trump",
        loggedIn: "true",
        workStatus: "",
        seatNo: "555",
      },
      {
        employeeId: "9",
        employeeName: "Ck",
        loggedIn: "true",
        workStatus: "",
        seatNo: "345",
      },
      {
        employeeId: "10",
        employeeName: "Swiss",
        loggedIn: "true",
        workStatus: "",
        seatNo: "980",
      },
      {
        employeeId: "11",
        employeeName: "Rana",
        loggedIn: "true",
        workStatus: "",
        seatNo: "999",
      },
      {
        employeeId: "12",
        employeeName: "Aman",
        loggedIn: "true",
        workStatus: "",
        seatNo: "654",
      },
      {
        employeeId: "13",
        employeeName: "Mikey",
        loggedIn: "true",
        workStatus: "",
        seatNo: "122",
      },
      {
        employeeId: "14",
        employeeName: "Weis",
        loggedIn: "true",
        workStatus: "",
        seatNo: "77",
      },
      {
        employeeId: "15",
        employeeName: "BB",
        loggedIn: "true",
        workStatus: "",
        seatNo: "66",
      },
      {
        employeeId: "16",
        employeeName: "Hina",
        loggedIn: "true",
        workStatus: "",
        seatNo: "3434",
      },
    ],
  },
};
